import Head from 'next/head';

import Header from '../header/Header';

interface LayoutProps {
  children?: React.ReactNode;
}

const RootLayout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Orca blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto max-w-3xl px-8 lg:max-w-6xl ">
        <Header />
        {children}
      </div>
    </>
  );
};

export default RootLayout;
