import Head from 'next/head';

import Footer from '../footer';
import Header from '../header';

interface LayoutProps {
  children?: React.ReactNode;
}

const RootLayout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Orca blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative mx-auto flex min-h-full max-w-5xl flex-col">
        <Header />
        <div className="pb-28">{children}</div>
        <Footer />
      </div>
    </>
  );
};

export default RootLayout;
