import Head from 'next/head';
import { useTheme } from 'next-themes';

import RootLayout from '@/libs/common/components/layout/RootLayout';

export default function Home() {
  const { theme, setTheme } = useTheme();

  return (
    <>
      <Head>
        <title>Andrevile Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RootLayout>
        <button
          onClick={() => (theme == 'dark' ? setTheme('light') : setTheme('dark'))}
          className="bottom-32 rounded-lg bg-gray-800 px-8 py-2 text-2xl text-white transition-all duration-100 hover:bg-gray-600 dark:bg-gray-50 dark:text-pink-800 dark:hover:bg-gray-300 md:text-4xl"
        >
          Toggle Mode
        </button>
        dfsadasfsfd
      </RootLayout>
      {/*       
      <main>
        <div>
          <p>
            <button
              onClick={() => (theme == 'dark' ? setTheme('light') : setTheme('dark'))}
              className="px-8 py-2 text-2xl text-white transition-all duration-100 bg-gray-800 rounded-lg bottom-32 hover:bg-gray-600 dark:bg-gray-50 dark:text-pink-800 dark:hover:bg-gray-300 md:text-4xl"
            >
              Toggle Mode
            </button>
            Get started by editing&nbsp;
            <code>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By <Image src="/vercel.svg" alt="Vercel Logo" width={100} height={24} priority />
            </a>
          </div>
        </div>

        <div>
          <Image src="/next.svg" alt="Next.js Logo" width={180} height={37} priority />
        </div>

        <div>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>Find in-depth information about Next.js features and&nbsp;API.</p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>Learn about Next.js in an interactive course with&nbsp;quizzes!</p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>Discover and deploy boilerplate example Next.js&nbsp;projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>Instantly deploy your Next.js site to a shareable URL with&nbsp;Vercel.</p>
          </a>
        </div>
      </main> */}
    </>
  );
}
