import Head from 'next/head';

import RootLayout from '@/libs/components/layout/RootLayout';

export default function Home() {
  return (
    <>
      <Head>
        <title>Andrevile Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RootLayout>
        {/* <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div> */}
        {/* <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div>
        <div className="h-24 bg-blue-200">dfsafa</div> */}
        <div className="h-24 bg-red-200">dfsafa</div>
      </RootLayout>
    </>
  );
}
